# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-25 14:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_auto_20180125_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='admin_user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
