# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-22 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('origin', models.CharField(default='Cairo', max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('departing_date', models.DateField()),
                ('returning_date', models.DateField()),
                ('transportstion', models.CharField(choices=[('B', 'Bus'), ('T', 'Train'), ('P', 'Plane'), ('S', 'Ship')], max_length=10)),
                ('residence', models.CharField(choices=[('M', 'Motel'), ('T', '3 star Hotel'), ('F', '4 star Hotel'), ('V', '5 star Hotel'), ('N', 'N/N')], max_length=20)),
                ('price', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
