# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-24 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_auto_20180122_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='trip_image1',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_image2',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_image3',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
