# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-24 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_auto_20180124_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='departing_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='returning_date',
            field=models.DateTimeField(),
        ),
    ]
