# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-24 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_auto_20180124_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_image1',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_image2',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_image3',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
    ]
