# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-24 13:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_auto_20180124_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='reservation',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
