# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-26 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_auto_20180124_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='Q_content',
            field=models.TextField(max_length=500),
        ),
    ]
