# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-28 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0010_auto_20180127_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='description',
            field=models.TextField(max_length=5000, null=True),
        ),
    ]
