# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-30 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0012_auto_20180130_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='reply_to',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='trips.Question'),
        ),
    ]
