# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-30 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0013_question_reply_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='reply_to',
            field=models.PositiveSmallIntegerField(default='0'),
        ),
    ]
