# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-01 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0014_auto_20180130_1848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='number',
            new_name='persons',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='adult_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='kid_price',
        ),
        migrations.AddField(
            model_name='reservation',
            name='totalprice',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
